# GitHub Sponsors username
github: []

# Patreon username
patreon:

# Open Collective
open_collective:

# Ko-fi username
ko_fi:

# Tidelift platform name/package
tidelift:

# Community Bridge project name
community_bridge:

# Liberapay username
liberapay:

# IssueHunt username
issuehunt:

# Otechie username
otechie:

# Custom sponsorship links
custom:
  - https://codetalesafrica.com
